version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/build

permissions:
    - object: /
      pattern: "**"
      owner: ubuntu
      group: ubuntu

hooks:
    BeforeInstall:
        - location: /scripts/initialize.sh
          runas: ubuntu

    ApplicationStart:
        - location: /scripts/start.sh
          runas: ubuntu
